# Standard Library
from os import getenv


MEMBER_PROCESS = 1
CONJUGAL_PROCESS = 2
CHILDREN_PROCESS = 3

MEMBERS_TABLE = "family_members"
CONJUGAL_TABLE = "conjugals"
CHILDREN_TABLE = "conjugals_children"

MEMBER_CSV = "clan_data.csv"
CONJUGAL_CSV = "clan_data_conjugal.csv"
CHILDREN_CSV = "clan_data_conjugal_children.csv"

FAMILY_PROCESSES_TABLES = {
    MEMBER_PROCESS: MEMBERS_TABLE,
    CONJUGAL_PROCESS: CONJUGAL_TABLE,
    CHILDREN_PROCESS: CHILDREN_TABLE,
}

FAMILY_PROCESSES_CSV = {
    MEMBER_PROCESS: MEMBER_CSV,
    CONJUGAL_PROCESS: CONJUGAL_CSV,
    CHILDREN_PROCESS: CHILDREN_CSV,
}

POSTGRESQL_USER = getenv("POSTGRESQL_USER", "")
POSTGRESQL_PASSWORD = getenv("POSTGRESQL_PASSWORD", "")
POSTGRESQL_SERVER = getenv("POSTGRESQL_SERVER")
POSTGRESQL_DATABASE = getenv("POSTGRESQL_DATABASE", "")
POSTGRESQL_PORT = getenv("POSTGRESQL_PORT", 5432)
